Importazione librerie utili all'analisi

In [3]:
import yfinance as yf

Inserire i dati di interesse

In [39]:
ticker_NEW='GME' #selezionare il ticker d'interesse
start_NEW = '2021-06-12' #selezionare la data iniziale del periodo d'interesse ('YYYY-MM-DD')
end_NEW='2021-06-25' #selezionare la data finale del periodo di interesse ('YYYY-MM-DD')
interval_NEW='15m' #selezionare la granularità dei dati

Definizione di una funzione e sua esecuzione per ottenere i dati finanziari

In [44]:
def getfinancialData(ticker,inizio,fine,intervallo):
    tick=yf.Ticker(ticker)
    historicaldata=tick.history(start=inizio,end=fine,interval=intervallo)
    return historicaldata
getfinancialData(ticker_NEW,start_NEW,end_NEW,interval_NEW)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2021-06-14 09:30:00-04:00,236.500000,238.009995,223.000000,225.009995,1141109,0,0
2021-06-14 09:45:00-04:00,225.104996,229.259995,224.020004,226.820007,507841,0,0
2021-06-14 10:00:00-04:00,226.837204,232.721207,224.800003,229.509995,452580,0,0
2021-06-14 10:15:00-04:00,229.509995,231.000000,222.500000,224.440002,415211,0,0
2021-06-14 10:30:00-04:00,224.360001,226.740005,220.179993,223.000000,409660,0,0
...,...,...,...,...,...,...,...
2021-06-24 14:45:00-04:00,213.710495,214.273605,212.600006,214.000000,133063,0,0
2021-06-24 15:00:00-04:00,213.899994,215.000000,213.800003,214.339996,114596,0,0
2021-06-24 15:15:00-04:00,214.563705,215.000000,212.800095,213.250107,110064,0,0
2021-06-24 15:30:00-04:00,213.429993,213.570007,212.399994,212.710098,126986,0,0
2021-06-24 15:45:00-04:00,212.767807,213.000000,211.600006,212.339996,289302,0,0

Salvare i dati in csv, specificando un determinato percorso

In [43]:
gme_historicaldata.to_csv(r'C:/Users/39345/Desktop/Data Science/Data Management/Progetto/gmeyfinance.csv')